### ISSUE TITLE
data: analytics, experimentation, user journeys

### ISSUE THREAD

**Issue by tomholford** [tloncorp/landscape-apps#2002]
# Context

We are currently flying blind and have little insight into:

- how users are navigating and using Groups, Talk, Notes, and Galleries
- what features are heaviliy used and deserve more attention
- which are a waste of resources and should be deprioritized or deprecated

# Changes

- [ ] add toggle to allow user to opt-in to telemetry
- [ ] add JS script to frontend client to collect user journeys & clickstreams
- [ ] POST events from backend agent to PostHog
- [ ] fire events at key stages of the user journey (e.g., user created a group, user generated an invite link)
- [ ] build funnels based on aforementioned events in PostHog for analysis and future iteration
- [ ] use A/B testing to experiment new ideas or designs

# TODO

- [ ] which business questions are we trying to answer? which funnels do we care about? what are the key stages of those funnels?

**Comment by lukestiles** [comment]
This one is in the future and contingent on how we communicate around this. clear web is first. :)
